/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.text.DecimalFormat;

/**
 *
 * @author user21
 */
public class conversorTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form conversorTemperatura
     */
    
    int queConversionInicial, queConversionFinal;
    double gradosIniciales, gradosFinales;
    
    public conversorTemperatura() {
        initComponents();
        
        this.setLocationRelativeTo(null); 
        temperaturaInicial.setHorizontalAlignment(temperaturaInicial.RIGHT);
        temperaturaResultado.setHorizontalAlignment(temperaturaResultado.RIGHT);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTemperatura = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        imagenTemperatura = new javax.swing.JLabel();
        etiquetaInstruccion = new javax.swing.JLabel();
        seleccionConversionInicial = new javax.swing.JComboBox<>();
        botonRegresar = new javax.swing.JButton();
        temperaturaInicial = new javax.swing.JTextField();
        seleccionConversionFinal = new javax.swing.JComboBox<>();
        temperaturaResultado = new javax.swing.JTextField();
        instruccionResultado = new javax.swing.JLabel();
        etiquetaDeHacia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversor Temperaturas");
        setResizable(false);

        panelTemperatura.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaTitulo.setText("CONVERSOR DE TEMPERATURA");

        imagenTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        imagenTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/temperatura.png"))); // NOI18N

        etiquetaInstruccion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiquetaInstruccion.setText("Grados a convertir");

        seleccionConversionInicial.setBackground(new java.awt.Color(204, 204, 255));
        seleccionConversionInicial.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        seleccionConversionInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius (C)", "Fahrenheit (F)", "Kelvin (K)" }));
        seleccionConversionInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionConversionInicialActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/izquierda.png"))); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        temperaturaInicial.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        temperaturaInicial.setToolTipText("Ingrese solo números");
        temperaturaInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temperaturaInicialKeyTyped(evt);
            }
        });

        seleccionConversionFinal.setBackground(new java.awt.Color(204, 204, 255));
        seleccionConversionFinal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        seleccionConversionFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius (C)", "Fahrenheit (F)", "Kelvin (K)" }));
        seleccionConversionFinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seleccionConversionFinalItemStateChanged(evt);
            }
        });
        seleccionConversionFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionConversionFinalMouseClicked(evt);
            }
        });
        seleccionConversionFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionConversionFinalActionPerformed(evt);
            }
        });

        temperaturaResultado.setEditable(false);
        temperaturaResultado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        temperaturaResultado.setToolTipText("Ingrese solo números");

        instruccionResultado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        instruccionResultado.setText("Resultado");

        etiquetaDeHacia.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiquetaDeHacia.setText("a");

        javax.swing.GroupLayout panelTemperaturaLayout = new javax.swing.GroupLayout(panelTemperatura);
        panelTemperatura.setLayout(panelTemperaturaLayout);
        panelTemperaturaLayout.setHorizontalGroup(
            panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTemperaturaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonRegresar)
                    .addGroup(panelTemperaturaLayout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(imagenTemperatura))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTemperaturaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(instruccionResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(temperaturaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTemperaturaLayout.createSequentialGroup()
                        .addComponent(seleccionConversionInicial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaDeHacia)
                        .addGap(23, 23, 23)
                        .addComponent(seleccionConversionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTemperaturaLayout.createSequentialGroup()
                        .addComponent(etiquetaInstruccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperaturaInicial)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelTemperaturaLayout.setVerticalGroup(
            panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTemperaturaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagenTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaInstruccion)
                    .addComponent(temperaturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionConversionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionConversionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDeHacia))
                .addGap(27, 27, 27)
                .addGroup(panelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperaturaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instruccionResultado))
                .addGap(26, 26, 26)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void temperaturaInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temperaturaInicialKeyTyped
     
        char []soloNumeros = {'1','2','3','4','5','6','7','8','9','0','.'};

        int comparador=0;

        for(int i=0;i<=10;i++){
            if (soloNumeros[i]==evt.getKeyChar()){
                comparador=1;
            }
        }

        if(comparador==0) {
            evt.consume();  
            getToolkit().beep(); 
         }    
        
    }//GEN-LAST:event_temperaturaInicialKeyTyped

    private void seleccionConversionInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionConversionInicialActionPerformed
     
        int idSeleccionI = seleccionConversionInicial.getSelectedIndex();
        
       switch (idSeleccionI){
           
            case 0:                
                queConversionInicial = 0;
               break;
            
            case 1:
                queConversionInicial = 1;
                break;
                
            case 2:
                 queConversionInicial = 2;
                break;
       
        default:
            throw new AssertionError();
       }    
       
       
        switch (queConversionInicial) {
            case 0:
                seleccionConversionFinal.setSelectedIndex(1);                
                break;
                
            case 1:
                seleccionConversionFinal.setSelectedIndex(0);
                break;

            case 2:
                seleccionConversionFinal.setSelectedIndex(0);                
                
                break;                
                
            default:
                throw new AssertionError();
        }
        
        
    }//GEN-LAST:event_seleccionConversionInicialActionPerformed

    private void seleccionConversionFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionConversionFinalActionPerformed
       
        temperaturaResultado.setText("");
        gradosIniciales = Double.parseDouble(temperaturaInicial.getText());
        calculos(gradosIniciales, queConversionInicial, queConversionFinal);         
        
    }//GEN-LAST:event_seleccionConversionFinalActionPerformed

    private void seleccionConversionFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionConversionFinalMouseClicked
                
    }//GEN-LAST:event_seleccionConversionFinalMouseClicked

    private void seleccionConversionFinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seleccionConversionFinalItemStateChanged

        int idSeleccionF = seleccionConversionFinal.getSelectedIndex();
        
        switch (idSeleccionF){
           
            case 0:                
                queConversionFinal = 0;
                
               break;
            
            case 1:
                queConversionFinal = 1;
                break;
                
            case 2:
                 queConversionFinal = 2;
                break;
       
            default:
            throw new AssertionError();
        }
        
        

    }//GEN-LAST:event_seleccionConversionFinalItemStateChanged


public void calculos(double gradosIniciales, int cInicial, int cFinal){


    if(cInicial==0){
        
        if(cFinal==1){
            gradosFinales = (gradosIniciales * 9/5) + 32;
        }
        
        else{
            if(cFinal==2){
                gradosFinales = (gradosIniciales + 273.15);
            }
            
            else{gradosFinales=gradosIniciales;}            
        }
    }
    
    else{

        if(cInicial==1){

            if(cFinal==0){
                gradosFinales = (gradosIniciales - 32) * 5/9;
            }

            else{
                if(cFinal==2){
                    gradosFinales = (gradosIniciales -32) * 5/9 + 273.15;
                }
                
                else{gradosFinales=gradosIniciales;}
            }
        }
        
        else{

            if(cInicial==2){

                if(cFinal==0){
                    gradosFinales = (gradosIniciales - 273.15);
                }

                else{
                    if(cFinal==1){
                        gradosFinales = (gradosIniciales - 273.15) * 9/5 + 32;
                    }
                    
                    else{gradosFinales=gradosIniciales;}                    
                }
            }                    
        }        
    }
    
    DecimalFormat formato = new DecimalFormat("#.####");
    temperaturaResultado.setText(String.valueOf(formato.format(gradosFinales)));
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel etiquetaDeHacia;
    private javax.swing.JLabel etiquetaInstruccion;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel imagenTemperatura;
    private javax.swing.JLabel instruccionResultado;
    private javax.swing.JPanel panelTemperatura;
    private javax.swing.JComboBox<String> seleccionConversionFinal;
    private javax.swing.JComboBox<String> seleccionConversionInicial;
    private javax.swing.JTextField temperaturaInicial;
    private javax.swing.JTextField temperaturaResultado;
    // End of variables declaration//GEN-END:variables


}
